name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: >-
          --health-cmd "rabbitmq-diagnostics ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Check formatting
        run: go fmt ./...

      - name: Run vet
        run: go vet ./...

      - name: Run unit tests
        run: make unit-test

      - name: Run examples app test
        run: make examples-app-test

      - name: Wait for RabbitMQ and Redis to be healthy
        run: |
          for i in {1..10}; do
            rabbitmq_status=$(docker inspect --format='{{.State.Health.Status}}' $(docker ps -q --filter name=rabbitmq))
            redis_status=$(docker inspect --format='{{.State.Health.Status}}' $(docker ps -q --filter name=redis))
            if [[ "$rabbitmq_status" == "healthy" && "$redis_status" == "healthy" ]]; then
              echo "✅ Both RabbitMQ and Redis are healthy!"
              break
            fi
            echo "⏳ Waiting for services..."
            sleep 5
          done

      - name: Run integration tests (RabbitMQ + Redis)
        run: make integration-test
